import time
from selenium import webdriver

driver = webdriver.Chrome()
driver.maximize_window()
driver.get("http://practice.automationtesting.in/")
driver.implicitly_wait(10)
driver.execute_script("window.scrollBy(0,600);")
ruby_btn = driver.find_element_by_class_name("woocommerce-LoopProduct-link")
ruby_btn.click()
reviews_btn = driver.find_element_by_class_name("reviews_tab > a")
reviews_btn.click()
rate_btn = driver.find_element_by_class_name("star-5")
rate_btn.click()
comment = driver.find_element_by_id("comment")
comment.send_keys("Nice book!")
author = driver.find_element_by_id("author")
author.send_keys("Eugene")
email = driver.find_element_by_id("email")
email.send_keys("evgeniy.online@mail.ru")
submit_btn = driver.find_element_by_id("submit")
submit_btn.click()
time.sleep(5)
driver.quit()
